# Use an official Python runtime as a parent image
FROM python:3.10.13

# Set the working directory in the container
# Set the working directory in the container
WORKDIR /app

# Install TA-Lib dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    wget

# Download and install TA-Lib
RUN wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz && \
    tar -xzf ta-lib-0.4.0-src.tar.gz && \
    cd ta-lib/ && \
    ./configure --prefix=/usr && \
    make && \
    make install

# Clean up the tar file and build directory
RUN rm -Rf ta-lib-0.4.0-src.tar.gz && rm -Rf ta-lib/

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run your_script.py when the container launches
CMD ["python", "./optimize.py"]
